window.comparisonReportData = {
  pageTitle: 'GLM-5-Turbo vs GLM-5.1 vs GPT-5.4 vs GPT-5.5（不思考） vs DeepSeek V4 Pro vs MiniMax-M2.7 vs Grok 4.20 Beta | Silicon Rider Bench',
  headerBadge: 'Silicon Rider Bench — Level 1 · 24h Simulation',
  subtitle: '七款 AI 外卖骑手智能体全维度性能对比 · 最新加入 DeepSeek V4 Pro',
  models: [
    {
      id: 'turbo',
      toneClass: 'turbo',
      name: 'GLM-5-Turbo',
      toneTextClass: 'turbo-text',
      tableToneClass: 'turbo-color',
      seed: 54039,
      runtime: '~27min',
      calls: 444,
      profit: '¥347.27',
      chart: {
        color: '#f97316',
        bg: 'rgba(249,115,22,0.15)',
        border: 'rgba(249,115,22,0.85)',
        overlayBg: 'rgba(249,115,22,0.08)',
        overlayBorder: 'rgba(249,115,22,0.7)',
      },
      radarInputs: {
        profit: 347.27,
        onTimeRate: 29.4,
        pathEfficiency: 1.94,
        apiViolationRate: 1.8,
        avgProfitPerOrder: 10.21,
        avgOvertimeMinutes: 27.1,
      },
      cardStats: [
        { label: '完成订单', value: '34' },
        { label: '准时率', value: '29.4%', valueTone: 'red' },
        { label: '路径效率', value: '1.94' },
        { label: '总惩罚', value: '¥228.87', valueTone: 'red' },
      ],
      behaviorTag: 'TURBO',
      behaviorItems: ['偏爱大量距离计算', '分析多但落地慢', '时效管理明显偏弱', '利润与效率都处于中下游'],
      tokenUsage: {
        value: '1.05M',
        sub: '444 calls · 2362 tokens/call',
      },
    },
    {
      id: 'glm51',
      toneClass: 'glm51',
      name: 'GLM-5.1',
      toneTextClass: 'glm51-text',
      tableToneClass: 'glm51-color',
      seed: 116063,
      runtime: '~97min',
      calls: 495,
      profit: '¥485.23',
      chart: {
        color: '#06b6d4',
        bg: 'rgba(6,182,212,0.15)',
        border: 'rgba(6,182,212,0.85)',
        overlayBg: 'rgba(6,182,212,0.08)',
        overlayBorder: 'rgba(6,182,212,0.7)',
      },
      radarInputs: {
        profit: 485.23,
        onTimeRate: 43.2,
        pathEfficiency: 1.38,
        apiViolationRate: 0.6,
        avgProfitPerOrder: 13.11,
        avgOvertimeMinutes: 12.7,
      },
      cardStats: [
        { label: '完成订单', value: '37' },
        { label: '准时率', value: '43.2%', valueTone: 'yellow' },
        { label: '路径效率', value: '1.38' },
        { label: '总惩罚', value: '¥117.17', valueTone: 'yellow' },
      ],
      behaviorTag: 'GLM-5.1',
      behaviorItems: ['路径规划最好', '接单/换电协同更成熟', '完成单数最多', '但时效不够稳定，惩罚仍偏高'],
      tokenUsage: {
        value: '1.10M',
        sub: '495 calls · 2225 tokens/call',
      },
    },
    {
      id: 'gpt54',
      toneClass: 'gpt54',
      name: 'GPT-5.4',
      toneTextClass: 'gpt54-text',
      tableToneClass: 'gpt54-color',
      seed: 923608,
      runtime: '~27min',
      calls: 562,
      profit: '¥552.19',
      winnerBadge: 'BEST',
      chart: {
        color: '#a855f7',
        bg: 'rgba(168,85,247,0.15)',
        border: 'rgba(168,85,247,0.85)',
        overlayBg: 'rgba(168,85,247,0.08)',
        overlayBorder: 'rgba(168,85,247,0.7)',
      },
      radarInputs: {
        profit: 552.19,
        onTimeRate: 90.3,
        pathEfficiency: 1.46,
        apiViolationRate: 1.1,
        avgProfitPerOrder: 17.81,
        avgOvertimeMinutes: 0.3,
      },
      cardStats: [
        { label: '完成订单', value: '31' },
        { label: '准时率', value: '90.3%', valueTone: 'green' },
        { label: '路径效率', value: '1.46' },
        { label: '总惩罚', value: '¥0.00', valueTone: 'green' },
      ],
      behaviorTag: 'GPT-5.4',
      behaviorItems: ['强时效意识，极少超时', '会放弃低性价比风险单', '每单利润最高', '整体表现最像"职业骑手"'],
      tokenUsage: {
        value: '1.03M',
        sub: '562 calls · 1838 tokens/call',
      },
    },
    {
      id: 'gpt55nt',
      toneClass: 'gpt55nt',
      name: 'GPT-5.5（不思考）',
      toneTextClass: 'gpt55nt-text',
      tableToneClass: 'gpt55nt-color',
      seed: 91997,
      runtime: '~25min',
      calls: 579,
      profit: '¥451.26',
      chart: {
        color: '#fb7185',
        bg: 'rgba(251,113,133,0.15)',
        border: 'rgba(251,113,133,0.85)',
        overlayBg: 'rgba(251,113,133,0.08)',
        overlayBorder: 'rgba(251,113,133,0.7)',
      },
      radarInputs: {
        profit: 451.26,
        onTimeRate: 51.5,
        pathEfficiency: 1.86,
        apiViolationRate: 0.5,
        avgProfitPerOrder: 13.67,
        avgOvertimeMinutes: 12.3,
      },
      cardStats: [
        { label: '完成订单', value: '33' },
        { label: '准时率', value: '51.5%', valueTone: 'yellow' },
        { label: '路径效率', value: '1.86' },
        { label: '总惩罚', value: '¥85.31', valueTone: 'yellow' },
      ],
      behaviorTag: 'GPT-5.5',
      behaviorItems: ['API 违规率最低（0.5%）', '总惩罚仅 ¥85.31，明显优于多数模型', '准时率 51.5%，处于中上水平', '但路径效率 1.86，路线规划仍偏弱'],
      tokenUsage: {
        value: '0.98M',
        sub: '579 calls · 1699 tokens/call',
      },
    },
    {
      id: 'deepseekv4pro',
      toneClass: 'deepseekv4pro',
      name: 'DeepSeek V4 Pro',
      toneTextClass: 'deepseekv4pro-text',
      tableToneClass: 'deepseekv4pro-color',
      seed: 333619,
      runtime: '~69min',
      calls: 518,
      profit: '¥380.58',
      chart: {
        color: '#6366f1',
        bg: 'rgba(99,102,241,0.15)',
        border: 'rgba(99,102,241,0.85)',
        overlayBg: 'rgba(99,102,241,0.08)',
        overlayBorder: 'rgba(99,102,241,0.7)',
      },
      radarInputs: {
        profit: 380.58,
        onTimeRate: 42.9,
        pathEfficiency: 1.22,
        apiViolationRate: 1.0,
        avgProfitPerOrder: 13.59,
        avgOvertimeMinutes: 16.7,
      },
      cardStats: [
        { label: '完成订单', value: '28' },
        { label: '准时率', value: '42.9%', valueTone: 'yellow' },
        { label: '路径效率', value: '1.22' },
        { label: '总惩罚', value: '¥124.18', valueTone: 'yellow' },
      ],
      behaviorTag: 'DEEPSEEK',
      behaviorItems: ['路径效率最佳（1.22）', '总行驶距离仅 350.9 km，路线非常紧凑', '总调用 518 次但 token 消耗最高', '利润中游，强规划但收益转化一般'],
      tokenUsage: {
        value: '2.04M',
        sub: '518 calls · 3939 tokens/call',
      },
    },
    {
      id: 'minimax',
      toneClass: 'minimax',
      name: 'MiniMax-M2.7',
      toneTextClass: 'minimax-text',
      tableToneClass: 'minimax-color',
      seed: 819100,
      runtime: '~20min',
      calls: 313,
      profit: '¥332.88',
      chart: {
        color: '#10b981',
        bg: 'rgba(16,185,129,0.15)',
        border: 'rgba(16,185,129,0.85)',
        overlayBg: 'rgba(16,185,129,0.08)',
        overlayBorder: 'rgba(16,185,129,0.7)',
      },
      radarInputs: {
        profit: 332.88,
        onTimeRate: 46.7,
        pathEfficiency: 1.82,
        apiViolationRate: 2.6,
        avgProfitPerOrder: 11.1,
        avgOvertimeMinutes: 23.9,
      },
      cardStats: [
        { label: '完成订单', value: '30' },
        { label: '准时率', value: '46.7%', valueTone: 'yellow' },
        { label: '路径效率', value: '1.82' },
        { label: '总惩罚', value: '¥194.85', valueTone: 'red' },
      ],
      behaviorTag: 'MINIMAX',
      behaviorItems: ['速度快、总调用少', '但超时和惩罚偏高', '药店/超市单占比高', '属于可用但需要更稳调度的模型'],
      tokenUsage: {
        value: '0.95M',
        sub: '313 calls · 3049 tokens/call',
      },
    },
    {
      id: 'grok420',
      toneClass: 'grok420',
      name: 'Grok 4.20 Beta',
      toneTextClass: 'grok420-text',
      tableToneClass: 'grok420-color',
      seed: 218894,
      runtime: '~144min',
      calls: 328,
      profit: '¥323.64',
      chart: {
        color: '#3b82f6',
        bg: 'rgba(59,130,246,0.15)',
        border: 'rgba(59,130,246,0.85)',
        overlayBg: 'rgba(59,130,246,0.08)',
        overlayBorder: 'rgba(59,130,246,0.7)',
      },
      radarInputs: {
        profit: 323.64,
        onTimeRate: 41.4,
        pathEfficiency: 1.63,
        apiViolationRate: 2.1,
        avgProfitPerOrder: 11.16,
        avgOvertimeMinutes: 33.6,
      },
      cardStats: [
        { label: '完成订单', value: '29' },
        { label: '准时率', value: '41.4%', valueTone: 'yellow' },
        { label: '路径效率', value: '1.63' },
        { label: '总惩罚', value: '¥158.17', valueTone: 'red' },
      ],
      behaviorTag: 'GROK',
      behaviorItems: ['推理极长、决策缓慢', '总行驶距离最短、换电最少', '但超时最严重（均超 33.6min）', '路径规划好但时间管理差'],
      tokenUsage: {
        value: 'N/A',
        sub: '328 calls · xAI API 未报告 token 数',
      },
    },
  ],
  sections: {
    radar: {
      title: '六维能力雷达图',
      desc: '六个指标：盈利能力、准时率、路径效率、API规范性、单均利润、抗超时能力',
      labels: ['盈利能力', '准时率', '路径效率', 'API规范性', '单均利润', '抗超时能力'],
      normalizers: {
        profitDenominator: 600,
        pathEfficiencyMax: 2,
        avgProfitDenominator: 20,
        overtimeUpperBound: 40,
      },
    },
    radarOverlay: {
      title: '七模型叠加对比',
      desc: '同一坐标系下直观看出各模型的策略差异，GPT-5.4 仍以极高准时率领跑，DeepSeek V4 Pro 则在路径效率上最激进',
    },
    coreMetrics: {
      title: '核心指标对比',
      desc: '七模型同表比较，最优值高亮，最差值红色标注',
      conclusionTitle: '结论',
      rows: [
        { metric: '总利润', values: ['¥347.27', '¥485.23', '¥552.19', '¥451.26', '¥380.58', '¥332.88', '¥323.64'], bestModelId: 'gpt54', bestTone: 'gpt54-color', worstModelId: 'grok420', conclusion: { tone: 'up', text: 'GPT-5.4 最高' } },
        { metric: '完成订单数', values: ['34', '37', '31', '33', '28', '30', '29'], bestModelId: 'glm51', bestTone: 'glm51-color', worstModelId: 'deepseekv4pro', conclusion: { tone: 'neutral', text: 'GLM-5.1 最多' } },
        { metric: '准时率', values: ['29.4%', '43.2%', '90.3%', '51.5%', '42.9%', '46.7%', '41.4%'], bestModelId: 'gpt54', bestTone: 'green', worstModelId: 'turbo', conclusion: { tone: 'up', text: 'GPT-5.4 碾压' } },
        { metric: '路径效率', values: ['1.94', '1.38', '1.46', '1.86', '1.22', '1.82', '1.63'], bestModelId: 'deepseekv4pro', bestTone: 'deepseekv4pro-color', worstModelId: 'turbo', conclusion: { tone: 'up', text: 'DeepSeek V4 Pro 最优' } },
        { metric: 'API 违规率', values: ['1.8%', '0.6%', '1.1%', '0.5%', '1.0%', '2.6%', '2.1%'], bestModelId: 'gpt55nt', bestTone: 'gpt55nt-color', worstModelId: 'minimax', conclusion: { tone: 'up', text: 'GPT-5.5（不思考）最规范' } },
        { metric: '总行驶距离', values: ['638.4 km', '529.5 km', '487.4 km', '529.0 km', '350.9 km', '583.6 km', '479.2 km'], bestModelId: 'deepseekv4pro', bestTone: 'deepseekv4pro-color', worstModelId: 'turbo', conclusion: { tone: 'up', text: 'DeepSeek V4 Pro 最短' } },
        { metric: '换电次数', values: ['14', '12', '10', '11', '8', '12', '7'], bestModelId: 'grok420', bestTone: 'grok420-color', worstModelId: 'turbo', conclusion: { tone: 'up', text: 'Grok 最少' } },
        { metric: '总收入', values: ['¥354.27', '¥491.23', '¥557.19', '¥456.76', '¥384.58', '¥338.88', '¥327.14'], bestModelId: 'gpt54', bestTone: 'gpt54-color', worstModelId: 'grok420', conclusion: { tone: 'up', text: 'GPT-5.4 最高' } },
        { metric: '总惩罚', values: ['¥228.87', '¥117.17', '¥0.00', '¥85.31', '¥124.18', '¥194.85', '¥158.17'], bestModelId: 'gpt54', bestTone: 'green', worstModelId: 'turbo', conclusion: { tone: 'up', text: 'GPT-5.4 零惩罚' } },
        { metric: '平均每单利润', values: ['¥10.21', '¥13.11', '¥17.81', '¥13.67', '¥13.59', '¥11.10', '¥11.16'], bestModelId: 'gpt54', bestTone: 'gpt54-color', worstModelId: 'turbo', conclusion: { tone: 'up', text: 'GPT-5.4 最高效' } },
        { metric: '超时订单数', values: ['24', '21', '3', '16', '16', '16', '17'], bestModelId: 'gpt54', bestTone: 'green', worstModelId: 'turbo', conclusion: { tone: 'up', text: 'GPT-5.4 远少于其他' } },
        { metric: '平均超时时长', values: ['27.1 min', '12.7 min', '0.3 min', '12.3 min', '16.7 min', '23.9 min', '33.6 min'], bestModelId: 'gpt54', bestTone: 'green', worstModelId: 'grok420', conclusion: { tone: 'up', text: 'GPT-5.4 近乎零超时' } },
      ],
    },
    insights: {
      title: '关键发现',
      desc: '新增 DeepSeek V4 Pro 后，GPT-5.4 仍是利润王者；DeepSeek V4 Pro 则在路径效率和总路程上刷新最优',
      items: [
        {
          icon: '💰',
          title: '利润王者：GPT-5.4',
          bigNumber: '¥552.19',
          bigNumberClass: 'purple',
          text: '七模型里利润最高，且总惩罚为 0，不靠冒险刷单，靠稳定准时兑现收入。',
        },
        {
          icon: '⏱️',
          title: '准时率断层领先',
          bigNumber: '90.3%',
          bigNumberClass: 'green',
          text: 'GPT-5.4 的准时率是其他模型的两倍以上，直接决定了零惩罚结果。',
        },
        {
          icon: '🧭',
          title: '路径规划最好：DeepSeek V4 Pro',
          bigNumber: '1.22',
          bigNumberClass: 'indigo',
          text: 'DeepSeek V4 Pro 的路径效率来到 1.22，是七模型里最接近理论最优路线的一次，行驶距离也压到 350.9 km。',
        },
        {
          icon: '🛡️',
          title: '最规范：GPT-5.5（不思考）',
          bigNumber: '0.5%',
          bigNumberClass: 'rose',
          text: 'GPT-5.5（不思考）的 API 违规率降到 0.5%，是七模型里最低，同时总惩罚也仅 ¥85.31。',
        },
        {
          icon: '🛣️',
          title: 'Grok：距离最短但超时最狠',
          bigNumber: '479.2 km',
          bigNumberClass: 'blue',
          text: '虽然 DeepSeek V4 Pro 已拿下最短总路程，但 Grok 依然以仅 7 次换电保持最强电量管理；同时其平均超时 33.6 分钟仍为所有模型最差。',
        },
        {
          icon: '🎯',
          title: '高质量完成优于高数量完成',
          bigNumber: '31 单',
          bigNumberClass: 'purple',
          text: 'GPT-5.4 完成单数不是最多，却拿到最高利润，"少而准"比"多而迟"更值钱。',
        },
      ],
    },
    tokenConsumption: {
      title: 'Token 与工具消耗',
    },
    behavior: {
      title: '行为风格分析',
      desc: '从结果层面概括七款模型的策略倾向',
    },
    orderTypes: {
      title: '订单类型分布',
      rows: [
        { orderType: '🍽 餐饮订单', values: ['27 (79.4%)', '33 (89.2%)', '27 (87.1%)', '25 (75.8%)', '22 (78.6%)', '18 (60.0%)', '21 (72.4%)'] },
        { orderType: '🛒 超市订单', values: ['5 (14.7%)', '1 (2.7%)', '3 (9.7%)', '7 (21.2%)', '3 (10.7%)', '6 (20.0%)', '4 (13.8%)'] },
        { orderType: '💊 药店订单', values: ['2 (5.9%)', '3 (8.1%)', '1 (3.2%)', '1 (3.0%)', '3 (10.7%)', '6 (20.0%)', '4 (13.8%)'] },
      ],
    },
    footer: {
      note: '⚠️ 注意：七次运行使用不同种子（54039 / 116063 / 923608 / 91997 / 333619 / 819100 / 218894），地图与订单分布不同，非严格同条件对比',
      text: 'Silicon Rider Bench · KCORES Agent Benchmark · Updated with DeepSeek V4 Pro',
    },
  },
};
