window.comparisonReportData = {
  pageTitle: 'GLM-5-Turbo vs GLM-5.1 vs GPT-5.4 vs MiniMax-M2.7 | Silicon Rider Bench',
  headerBadge: 'Silicon Rider Bench — Level 1 · 24h Simulation',
  subtitle: '四款 AI 外卖骑手智能体全维度性能对比 · 最新已加入 MiniMax-M2.7',
  models: [
    {
      id: 'turbo',
      toneClass: 'turbo',
      name: 'GLM-5-Turbo',
      toneTextClass: 'turbo-text',
      tableToneClass: 'turbo-color',
      seed: 54039,
      runtime: '~27min',
      calls: 444,
      profit: '¥347.27',
      chart: {
        color: '#f97316',
        bg: 'rgba(249,115,22,0.15)',
        border: 'rgba(249,115,22,0.85)',
        overlayBg: 'rgba(249,115,22,0.08)',
        overlayBorder: 'rgba(249,115,22,0.7)',
      },
      radarInputs: {
        profit: 347.27,
        onTimeRate: 29.4,
        pathEfficiency: 1.94,
        apiViolationRate: 1.8,
        avgProfitPerOrder: 10.21,
        avgOvertimeMinutes: 27.1,
      },
      cardStats: [
        { label: '完成订单', value: '34' },
        { label: '准时率', value: '29.4%', valueTone: 'red' },
        { label: '路径效率', value: '1.94' },
        { label: '总惩罚', value: '¥228.87', valueTone: 'red' },
      ],
      behaviorTag: 'TURBO',
      behaviorItems: ['偏爱大量距离计算', '分析多但落地慢', '时效管理明显偏弱', '利润与效率都处于中下游'],
      tokenUsage: {
        value: '1.05M',
        sub: '444 calls · 2362 tokens/call',
      },
    },
    {
      id: 'glm51',
      toneClass: 'glm51',
      name: 'GLM-5.1',
      toneTextClass: 'glm51-text',
      tableToneClass: 'glm51-color',
      seed: 116063,
      runtime: '~97min',
      calls: 495,
      profit: '¥485.23',
      chart: {
        color: '#06b6d4',
        bg: 'rgba(6,182,212,0.15)',
        border: 'rgba(6,182,212,0.85)',
        overlayBg: 'rgba(6,182,212,0.08)',
        overlayBorder: 'rgba(6,182,212,0.7)',
      },
      radarInputs: {
        profit: 485.23,
        onTimeRate: 43.2,
        pathEfficiency: 1.38,
        apiViolationRate: 0.6,
        avgProfitPerOrder: 13.11,
        avgOvertimeMinutes: 12.7,
      },
      cardStats: [
        { label: '完成订单', value: '37' },
        { label: '准时率', value: '43.2%', valueTone: 'yellow' },
        { label: '路径效率', value: '1.38' },
        { label: '总惩罚', value: '¥117.17', valueTone: 'yellow' },
      ],
      behaviorTag: 'GLM-5.1',
      behaviorItems: ['路径规划最好', '接单/换电协同更成熟', '完成单数最多', '但时效不够稳定，惩罚仍偏高'],
      tokenUsage: {
        value: '1.10M',
        sub: '495 calls · 2225 tokens/call',
      },
    },
    {
      id: 'gpt54',
      toneClass: 'gpt54',
      name: 'GPT-5.4',
      toneTextClass: 'gpt54-text',
      tableToneClass: 'gpt54-color',
      seed: 923608,
      runtime: '~27min',
      calls: 562,
      profit: '¥552.19',
      winnerBadge: 'BEST',
      chart: {
        color: '#a855f7',
        bg: 'rgba(168,85,247,0.15)',
        border: 'rgba(168,85,247,0.85)',
        overlayBg: 'rgba(168,85,247,0.08)',
        overlayBorder: 'rgba(168,85,247,0.7)',
      },
      radarInputs: {
        profit: 552.19,
        onTimeRate: 90.3,
        pathEfficiency: 1.46,
        apiViolationRate: 1.1,
        avgProfitPerOrder: 17.81,
        avgOvertimeMinutes: 0.3,
      },
      cardStats: [
        { label: '完成订单', value: '31' },
        { label: '准时率', value: '90.3%', valueTone: 'green' },
        { label: '路径效率', value: '1.46' },
        { label: '总惩罚', value: '¥0.00', valueTone: 'green' },
      ],
      behaviorTag: 'GPT-5.4',
      behaviorItems: ['强时效意识，极少超时', '会放弃低性价比风险单', '每单利润最高', '整体表现最像“职业骑手”'],
      tokenUsage: {
        value: '1.03M',
        sub: '562 calls · 1838 tokens/call',
      },
    },
    {
      id: 'minimax',
      toneClass: 'minimax',
      name: 'MiniMax-M2.7',
      toneTextClass: 'minimax-text',
      tableToneClass: 'minimax-color',
      seed: 819100,
      runtime: '~20min',
      calls: 313,
      profit: '¥332.88',
      chart: {
        color: '#10b981',
        bg: 'rgba(16,185,129,0.15)',
        border: 'rgba(16,185,129,0.85)',
        overlayBg: 'rgba(16,185,129,0.08)',
        overlayBorder: 'rgba(16,185,129,0.7)',
      },
      radarInputs: {
        profit: 332.88,
        onTimeRate: 46.7,
        pathEfficiency: 1.82,
        apiViolationRate: 2.6,
        avgProfitPerOrder: 11.1,
        avgOvertimeMinutes: 23.9,
      },
      cardStats: [
        { label: '完成订单', value: '30' },
        { label: '准时率', value: '46.7%', valueTone: 'yellow' },
        { label: '路径效率', value: '1.82' },
        { label: '总惩罚', value: '¥194.85', valueTone: 'red' },
      ],
      behaviorTag: 'MINIMAX',
      behaviorItems: ['速度快、总调用少', '但超时和惩罚偏高', '药店/超市单占比高', '属于可用但需要更稳调度的模型'],
      tokenUsage: {
        value: '0.95M',
        sub: '313 calls · 3049 tokens/call',
      },
    },
  ],
  sections: {
    radar: {
      title: '六维能力雷达图',
      desc: '六个指标：盈利能力、准时率、路径效率、API规范性、单均利润、抗超时能力',
      labels: ['盈利能力', '准时率', '路径效率', 'API规范性', '单均利润', '抗超时能力'],
      normalizers: {
        profitDenominator: 600,
        pathEfficiencyMax: 2,
        avgProfitDenominator: 20,
        overtimeUpperBound: 40,
      },
    },
    radarOverlay: {
      title: '四模型叠加对比',
      desc: '同一坐标系下直观看出 GPT-5.4 的准时率优势，以及 GLM-5.1 的路径效率优势',
    },
    coreMetrics: {
      title: '核心指标对比',
      desc: '四模型同表比较，最优值高亮',
      conclusionTitle: '结论',
      rows: [
        { metric: '总利润', values: ['¥347.27', '¥485.23', '¥552.19', '¥332.88'], bestModelId: 'gpt54', bestTone: 'gpt54-color', conclusion: { tone: 'up', text: 'GPT-5.4 最高' } },
        { metric: '完成订单数', values: ['34', '37', '31', '30'], bestModelId: 'glm51', bestTone: 'glm51-color', conclusion: { tone: 'neutral', text: 'GLM-5.1 最多' } },
        { metric: '准时率', values: ['29.4%', '43.2%', '90.3%', '46.7%'], bestModelId: 'gpt54', bestTone: 'green', conclusion: { tone: 'up', text: 'GPT-5.4 碾压' } },
        { metric: '路径效率', values: ['1.94', '1.38', '1.46', '1.82'], bestModelId: 'glm51', bestTone: 'green', conclusion: { tone: 'up', text: 'GLM-5.1 最优' } },
        { metric: 'API 违规率', values: ['1.8%', '0.6%', '1.1%', '2.6%'], bestModelId: 'glm51', bestTone: 'green', conclusion: { tone: 'up', text: 'GLM-5.1 最规范' } },
        { metric: '总行驶距离', values: ['638.4 km', '529.5 km', '487.4 km', '583.6 km'], bestModelId: 'gpt54', bestTone: 'green', conclusion: { tone: 'up', text: 'GPT-5.4 最短' } },
        { metric: '换电次数', values: ['14', '12', '10', '12'], bestModelId: 'gpt54', bestTone: 'green', conclusion: { tone: 'up', text: 'GPT-5.4 最少' } },
        { metric: '总收入', values: ['¥354.27', '¥491.23', '¥557.19', '¥338.88'], bestModelId: 'gpt54', bestTone: 'gpt54-color', conclusion: { tone: 'up', text: 'GPT-5.4 最高' } },
        { metric: '总惩罚', values: ['¥228.87', '¥117.17', '¥0.00', '¥194.85'], bestModelId: 'gpt54', bestTone: 'green', conclusion: { tone: 'up', text: 'GPT-5.4 零惩罚' } },
        { metric: '平均每单利润', values: ['¥10.21', '¥13.11', '¥17.81', '¥11.10'], bestModelId: 'gpt54', bestTone: 'gpt54-color', conclusion: { tone: 'up', text: 'GPT-5.4 最高效' } },
        { metric: '超时订单数', values: ['24', '21', '3', '16'], bestModelId: 'gpt54', bestTone: 'green', conclusion: { tone: 'up', text: 'GPT-5.4 远少于其他' } },
        { metric: '平均超时时长', values: ['27.1 min', '12.7 min', '0.3 min', '23.9 min'], bestModelId: 'gpt54', bestTone: 'green', conclusion: { tone: 'up', text: 'GPT-5.4 近乎零超时' } },
      ],
    },
    insights: {
      title: '关键发现',
      desc: '最新加入 MiniMax 后，整体格局没有变化：GPT-5.4 仍是绝对强者，GLM-5.1 在路径规划上保有优势',
      items: [
        {
          icon: '💰',
          title: '利润王者：GPT-5.4',
          bigNumber: '¥552.19',
          bigNumberClass: 'purple',
          text: '四模型里利润最高，且总惩罚为 0，说明它不靠冒险刷单，而是靠稳定准时兑现收入。',
        },
        {
          icon: '⏱️',
          title: '准时率断层领先',
          bigNumber: '90.3%',
          bigNumberClass: 'green',
          text: 'GPT-5.4 的准时率是 MiniMax 的近 2 倍，也是 GLM-5.1 的 2 倍以上，这直接决定了零惩罚结果。',
        },
        {
          icon: '🧭',
          title: '路径规划最好：GLM-5.1',
          bigNumber: '1.38',
          bigNumberClass: 'cyan',
          text: '单看路径效率，GLM-5.1 最接近理论最优路线；但它在时效管理上明显弱于 GPT-5.4。',
        },
        {
          icon: '⚡',
          title: 'MiniMax 速度快但稳定性一般',
          bigNumber: '~20 min',
          bigNumberClass: 'mint',
          text: 'MiniMax 用时最短、工具调用最少，但利润最低，且惩罚高达 ¥194.85，说明节奏快但调度粗糙。',
        },
        {
          icon: '📉',
          title: 'Turbo 与 MiniMax 接近',
          bigNumber: '¥347 vs ¥333',
          bigNumberClass: 'orange',
          text: '两者都属于“能跑通但不够稳”的梯队。Turbo 略强于 MiniMax，但两者都被 GPT-5.4 和 GLM-5.1 拉开。',
        },
        {
          icon: '🎯',
          title: '高质量完成优于高数量完成',
          bigNumber: '31 单',
          bigNumberClass: 'purple',
          text: 'GPT-5.4 完成单数不是最多，却拿到最高利润，说明“少而准”比“多而迟”更值钱。',
        },
      ],
    },
    tokenConsumption: {
      title: 'Token 与工具消耗',
    },
    behavior: {
      title: '行为风格分析',
      desc: '从结果层面概括四款模型的策略倾向',
    },
    orderTypes: {
      title: '订单类型分布',
      rows: [
        { orderType: '🍽 餐饮订单', values: ['27 (79.4%)', '33 (89.2%)', '27 (87.1%)', '18 (60.0%)'] },
        { orderType: '🛒 超市订单', values: ['5 (14.7%)', '1 (2.7%)', '3 (9.7%)', '6 (20.0%)'] },
        { orderType: '💊 药店订单', values: ['2 (5.9%)', '3 (8.1%)', '1 (3.2%)', '6 (20.0%)'] },
      ],
    },
    footer: {
      note: '⚠️ 注意：四次运行使用不同种子（54039 / 116063 / 923608 / 819100），地图与订单分布不同，非严格同条件对比',
      text: 'Silicon Rider Bench · KCORES Agent Benchmark · Updated with MiniMax-M2.7',
    },
  },
};
